load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

package(default_visibility = ["//visibility:public"])

kernel_module(
    name = "hynitron_recon",
    srcs = glob(["**/*"], exclude = ["BUILD.bazel", "*.ko", "*.o", "*.mod", "*.cmd"]),
    outs = ["hynitron.ko"],
    kernel_build = "//common:kernel_aarch64",
)
