load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

package(default_visibility = ["//visibility:public"])

kernel_module(
    name = "sh366003_recon",
    srcs = [
        "Makefile",
        "sh366003_fg.c",
        "sinofs_afi_data.inc",
        "stock-yft-devinfo.symvers",
    ],
    outs = ["sh366003_fg.ko"],
    kernel_build = "//common:kernel_aarch64",
)
