load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

package(default_visibility = ["//visibility:public"])

kernel_module(
    name = "sc8571_recon",
    srcs = [
        "Makefile",
        "charger_class_stock_abi.h",
        "charger_class-stock.symvers.h",
        "sc8571_charger.c",
    ],
    outs = ["sc8571_charger.ko"],
    kernel_build = "//common:kernel_aarch64",
)
