load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

package(default_visibility = ["//visibility:public"])

kernel_module(
    name = "yft_tiny2c_usb_recon",
    srcs = ["Makefile", "yft_tiny2c_usb.c"],
    outs = ["yft_tiny2c_usb.ko"],
    kernel_build = "//common:kernel_aarch64",
    deps = ["//lieppos/mt6375-charger-provider-abi:mt6375_charger_provider_abi"],
)
