load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

package(default_visibility = ["//visibility:public"])

kernel_module(
    name = "custom_ldo_recon",
    srcs = ["Makefile", "custom_ldo.c"],
    outs = ["custom_ldo.ko"],
    deps = [
        "//lieppos/custom-ldo-wl2868-recon/stock-name:custom_ldo_wl2868_stock_name",
    ],
    kernel_build = "//common:kernel_aarch64",
)
